version: 2
jobs:
  build:
    working_directory: ~/working_directory
    docker:
      - image: beevelop/android:latest
    environment:
      ANDROID_HOME: /opt/android
    steps:
      - checkout
      - run:
          name: System information
          command: |
            mkdir $ANDROID_HOME/licenses
            echo [ANDROID_SDK_LICENSE] >> $ANDROID_HOME/licenses/android-sdk-license
            echo y | android update sdk --no-ui --all --filter "build-tools-25.0.2"
            echo y | android update sdk --no-ui --all --filter "extra-android-m2repository,extra-google-m2repository"
      - run:
          name: Install dependencies
          command: ./gradlew dependencies
      - run:
          name: Build
          command: ./gradlew assembleRelease