version: 2
jobs:
  build:
    working_directory: ~/working_directory
    docker:
      - image: urbansitter/android-java8:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: ./gradlew dependencies
      - run:
          name: Build
          command: ./gradlew assembleRelease