version: 2
jobs:
  build:
    working_directory: ~/working_directory
    docker:
      - image: urbansitter/android-java8:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: ./gradlew dependencies
      - run:
          name: Build
          command: ./gradlew assembleDebug

      - deploy:
          hockey:
              commands:
                - ipa distribute:hockeyapp -m "test build" --token 7784ea63ac66466bb86de0b303dab0c9